name: SemVer and Trigger Infra Build

on:
  push:
    paths:
      - 'frontend-service/**'
    branches:
      - main

permissions:
  contents: write

jobs:
  version-and-dispatch:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend-service

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Git Identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install Dependencies
        run: npm install

      - name: Bump Version with Standard Version
        run: |
          npx standard-version
          git push --follow-tags origin main
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Trigger Infra Repo Build
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          VERSION: ${{ env.VERSION }}
        run: |
          curl -X POST https://api.github.com/repos/punnam14/recommendation-engine-infra-repo/dispatches \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d '{"event_type":"build-frontend", "client_payload":{"version":"v'"$VERSION"'"}}'