name: SemVer and Trigger Infra Build for Product Service

on:
  push:
    paths:
      - 'product-service/**'
    branches:
      - main

permissions:
  contents: write

jobs:
  version-and-dispatch:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./product-service

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Git Identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump Version (using .version file)
        run: |
          CURRENT_VERSION=$(cat .version 2>/dev/null || echo "0.0.0")
          echo "Current version: $CURRENT_VERSION"

          git fetch --prune --unshallow
          COMMITS=$(git log --pretty=format:"%s%n%b" origin/main..HEAD)
          if echo "$COMMITS" | grep -qE "BREAKING CHANGE|^feat!:"; then
            BUMP="major"
          elif echo "$COMMITS" | grep -qE "^feat"; then
            BUMP="minor"
          elif echo "$COMMITS" | grep -qE "^fix"; then
            BUMP="patch"
          else
            BUMP="patch"
          fi
          
          IFS='.' read -r MAJOR MINOR PATCH <<< "${CURRENT_VERSION}"
          if [ "$BUMP" = "major" ]; then
          MAJOR=$((MAJOR + 1)); MINOR=0; PATCH=0
          elif [ "$BUMP" = "minor" ]; then
            MINOR=$((MINOR + 1)); PATCH=0
          else
            PATCH=$((PATCH + 1))
          fi

          NEXT_VERSION="${MAJOR}.${MINOR}.${PATCH}"
          echo "Next version: $NEXT_VERSION"

          echo "$NEXT_VERSION" > .version
          git add .version
          git commit -m "chore(product): bump version to $NEXT_VERSION"
          git push origin main

          echo "VERSION=$NEXT_VERSION" >> $GITHUB_ENV

      - name: Trigger Infra Repo Build
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          VERSION: ${{ env.VERSION }}
        run: |
          curl -X POST https://api.github.com/repos/punnam14/recommendation-engine-infra-repo/dispatches \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d '{"event_type":"build-product", "client_payload":{"version":"'"$VERSION"'"}}'
